# -*- coding: utf-8 -*-
"""Email attachment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xsgou7B7hGmwmsL0ysaeUOuTCWGmuKzY
"""

!pip install secure-smtplib
!pip install emails
from google.colab import files
uploaded=files.upload()



#smtplib provides to send the emails
import email, smtplib, ssl

#To attach the files in the email (Ex- PDF, CSV files)
from email.mime.application import MIMEApplication
#It supports emails sending both Text and attachments
from email.mime.multipart import MIMEMultipart
#It supports emails sending with body of the email content
from email.mime.text import MIMEText

subject = "Email Subject"
sender_email = "muraliyakkati@gmail.com"
body = "This is the email body"
receipient_email = "garikipatisrihari@gmail.com"
sender_password = "qraw adyq woqa ammx" #For gmail need to create app password and give it here
smtp_server = 'smtp.gmail.com' #smtp server provides sending the gmail and it has the port number
smtp_port = 465
path_to_file = 'Form 15G.pdf'

message = MIMEMultipart()
message['subject'] = subject
message['from'] = sender_email
message['To'] = receipient_email
body_part = MIMEText(body)
message.attach(body_part)

with open(path_to_file,'rb') as file:
  #Attach the file with file name to the email
  message.attach(MIMEApplication(file.read(), Name="Form 15G.pdf"))

with smtplib.SMTP_SSL(smtp_server, smtp_port) as server:
  server.login(sender_email, sender_password) #Login function logins the application
  server.sendmail(sender_email, receipient_email, message.as_string()) # Sendmail function sends the gmail
  print("email sent")
  server.quit()